menu:
  home: /
  archive: /archives
  tags: /tags
  info: /about
  rss: /atom.xml

banner: http://7xpot0.com1.z0.glb.clouddn.com/17-2-15/85842234-file_1487150842287_e1fb.jpg
avatar: /avatar.png
favicon: /favicon.png
aboutme: 朝着前端打怪升级中 | 目前从事闪存产品的固件和测试工具开发工作 | 多特蒙德死忠

social:
  github: http://github.com/littlewin-wang
  twitter: http://twitter.com/littlewin_wang
  weibo: http://weibo.com/fredinweibo

# Comment
# e.g disqus: seansun
disqus:
duoshuo: littlewin

# Search
swift_search: true

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016