menu:
  home: /
  archive: /archives
  tags: /tags
  info: /about
  rss: /atom.xml

logo: /favicon.png
aboutme: 朝着前端打怪升级中 | 目前从事闪存产品的固件和测试工具开发工作 | 多特蒙德死忠

social:
  github: https://github.com/littlewin-wang
  twitter: #
  weibo: #

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
