menu:
  home: /
  archives: /archives
  tags: /tags
  about: /about
  rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

sign: SSD FW | 逆行->前端 | 多特死忠

social:
  github: https://github.com/littlewin-wang
  twitter: #
  weibo: #

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
